[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  functions = "../netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[build.environment]
  EMAIL_PASSWORD = 'pxse eool lyeu biqq'
  EMAIL_USER = 'mutai.brian79@gmail.com'
[dev]
  framework = "#custom"
  command = "npm --prefix frontend run dev"
  targetPort = 5000
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200