[build]
  command = "cd frontend && npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm --prefix frontend run dev"
  targetPort = 5000
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200